### ISSUE TITLE
No Input fields available

### ISSUE THREAD

**Issue by nothra** [TheAppleFreak/home-assistant-blueprints#1]
When using this blueprint creating a new script, no input fields are shown.

**Comment by TheAppleFreak** [comment]
If you create the script and then go to use it in an automation, the input fields should show up. With that said, I'll take a look at it and see what I can do to improve that!

**Comment by nothra** [comment]
Thank you for the hint. I only used the blueprint when creating a script and I missed these input fields.
Since this blueprint is for creating a script, I assumed that the input fields should already be visible.

Since I'm a beginner at scripting, I can't judge whether this is the right way to use the script blueprint in an automation.

**Comment by TheAppleFreak** [comment]
Admittedly this was the first (and so far only) script I've made for HA, so
I'm not entirely sure what best practice is either for that part of the
user flow. Frankly I don't think this is a script that necessarily needs
configuration at script creation time, though, but maybe there's a use case
out there that I haven't thought of. Regardless, some instructions and the
like are definitely a good idea if only to indicate things are working.

**Comment by TheAppleFreak** [comment]
Took a little while for me to remember to do this, but I just added a little introduction to the script! I think this should help significantly.
